artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: 'https://drive.google.com/file/d/1s2a0KK6nCC3sDZLtC3r7Y8RoW3jqmSsE/view?usp=drive_link'
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion